### ISSUE TITLE
Question about data

### ISSUE THREAD

**Issue by haoyanioz** [kristinmlee/dmc#2]
Dear developers,
Thanks for your code. Is it only suitable for population data, not suitable for genomic data of different closely related species? And how many individuals per population do we need for this analysis?

**Comment by kristinmlee** [comment]
Our method assumes that the sweeps are recent and that its effect on linked neutral variation is still detectable in the data. It may be used for populations within a species or between closely-related species, keeping this in mind. Additionally, if the species/populations are too far diverged, a variant that has been standing in their ancestor may effectively look like independent mutations since the independent recombination will result in very different haplotypes on which the beneficial alleles are on  across species/populations prior to selection (see the discussion of [our paper](http://www.genetics.org/content/207/4/1591) for more information). 

Regarding numbers of individuals per population, the method uses population allele frequencies and incorporates bias from sample size. Upwards of ten chromosomes per population to get sensible population allele frequencies seems reasonable, but I am not sure about the lowest limit needed. In the paper, we use population genomic samples with 20-50 diploid individuals per population.
